title: DevOpsDays Boston
email: boston@devopsdays.org
description: >- # this means to ignore newlines until "baseurl:"
  An ongoing series of yearly events for DevOps practitioners
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devopsdaysbos.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devopsdaysbos
github_username:  devopsdaysboston
show_github: false
google_analytics_tag: UA-137417319-8
produrl: "https://devopsdaysbos.org"
event_short_title: DevOpsDays Boston 2021
grandparent_site: https://devopsdays.org/events/2021-boston/welcome/

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages

atom_feed:
  hide: true
logo: "/assets/images/2021-logo.png"
masthead_title: "DevOpsDays Boston 2021"

# header_pages: []

current_event:
  dates: "Sept 27 & 28"
registration:
  is_open: true
  direct_link: "https://ti.to/devopsdaysbos/2021"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
